// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: company.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const banCompany = `-- name: BanCompany :exec
UPDATE "Company"
SET "isRestricted" = true
WHERE company_id = $1
`

func (q *Queries) BanCompany(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, banCompany, companyID)
	return err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO "Company" (
    company_name, company_phone, company_email, "address", "status"
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING company_id, company_name, company_phone, company_email, address, registered_date, status, created_at, updated_at, "isRestricted"
`

type CreateCompanyParams struct {
	CompanyName  string `json:"company_name"`
	CompanyPhone string `json:"company_phone"`
	CompanyEmail string `json:"company_email"`
	Address      string `json:"address"`
	Status       string `json:"status"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.CompanyName,
		arg.CompanyPhone,
		arg.CompanyEmail,
		arg.Address,
		arg.Status,
	)
	var i Company
	err := row.Scan(
		&i.CompanyID,
		&i.CompanyName,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Address,
		&i.RegisteredDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM "Company"
WHERE company_id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, companyID)
	return err
}

const getCompanies = `-- name: GetCompanies :many
SELECT company_name, company_phone, company_email, "status", created_at, updated_at, "isRestricted", "address"
FROM "Company"
ORDER BY company_id
LIMIT $1
OFFSET $2
`

type GetCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetCompaniesRow struct {
	CompanyName  string    `json:"company_name"`
	CompanyPhone string    `json:"company_phone"`
	CompanyEmail string    `json:"company_email"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
	Address      string    `json:"address"`
}

func (q *Queries) GetCompanies(ctx context.Context, arg GetCompaniesParams) ([]GetCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompaniesRow{}
	for rows.Next() {
		var i GetCompaniesRow
		if err := rows.Scan(
			&i.CompanyName,
			&i.CompanyPhone,
			&i.CompanyEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsRestricted,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT company_name, company_phone, company_email, "status", created_at, updated_at, "isRestricted", "address"
FROM "Company"
WHERE company_id = $1
LIMIT 1
`

type GetCompanyRow struct {
	CompanyName  string    `json:"company_name"`
	CompanyPhone string    `json:"company_phone"`
	CompanyEmail string    `json:"company_email"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
	Address      string    `json:"address"`
}

func (q *Queries) GetCompany(ctx context.Context, companyID uuid.UUID) (GetCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, getCompany, companyID)
	var i GetCompanyRow
	err := row.Scan(
		&i.CompanyName,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
		&i.Address,
	)
	return i, err
}

const getCompanyForUpdate = `-- name: GetCompanyForUpdate :one
SELECT company_name, company_phone, company_email, "status", created_at, updated_at, "isRestricted", "address" 
FROM "Company"
WHERE company_id = $1
LIMIT 1
FOR NO KEY UPDATE
`

type GetCompanyForUpdateRow struct {
	CompanyName  string    `json:"company_name"`
	CompanyPhone string    `json:"company_phone"`
	CompanyEmail string    `json:"company_email"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
	Address      string    `json:"address"`
}

func (q *Queries) GetCompanyForUpdate(ctx context.Context, companyID uuid.UUID) (GetCompanyForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyForUpdate, companyID)
	var i GetCompanyForUpdateRow
	err := row.Scan(
		&i.CompanyName,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
		&i.Address,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE "Company"
SET 
    company_name = COALESCE($2, company_name),
    company_phone = COALESCE($3, company_phone),
    company_email = COALESCE($4, company_email),
    "address" = COALESCE($5, "address"),
    "status" = COALESCE($6, "status"),
    "isRestricted" = COALESCE($7, "isRestricted"),
    updated_at = now()
WHERE company_id = $1
RETURNING company_name, company_phone, company_email, "status", created_at, updated_at,"address", "isRestricted"
`

type UpdateCompanyParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	CompanyName  string    `json:"company_name"`
	CompanyPhone string    `json:"company_phone"`
	CompanyEmail string    `json:"company_email"`
	Address      string    `json:"address"`
	Status       string    `json:"status"`
	IsRestricted bool      `json:"isRestricted"`
}

type UpdateCompanyRow struct {
	CompanyName  string    `json:"company_name"`
	CompanyPhone string    `json:"company_phone"`
	CompanyEmail string    `json:"company_email"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Address      string    `json:"address"`
	IsRestricted bool      `json:"isRestricted"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.CompanyID,
		arg.CompanyName,
		arg.CompanyPhone,
		arg.CompanyEmail,
		arg.Address,
		arg.Status,
		arg.IsRestricted,
	)
	var i UpdateCompanyRow
	err := row.Scan(
		&i.CompanyName,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.IsRestricted,
	)
	return i, err
}
