// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	AdminID      uuid.UUID `json:"admin_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Company struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CompanyName    string    `json:"company_name"`
	CompanyPhone   string    `json:"company_phone"`
	CompanyEmail   string    `json:"company_email"`
	Address        string    `json:"address"`
	RegisteredDate time.Time `json:"registered_date"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IsRestricted   bool      `json:"isRestricted"`
}

type OTPVerification struct {
	OtpID          uuid.UUID `json:"otp_id"`
	UserID         uuid.UUID `json:"user_id"`
	OtpCode        string    `json:"otp_code"`
	ExpiresAt      time.Time `json:"expires_at"`
	IsVerified     bool      `json:"is_verified"`
	FailedAttempts int32     `json:"failed_attempts"`
	CreatedAt      time.Time `json:"created_at"`
}

type Report struct {
	ReportID     uuid.UUID `json:"report_id"`
	UserID       uuid.UUID `json:"user_id"`
	CompanyID    uuid.UUID `json:"company_id"`
	ReportReason string    `json:"report_reason"`
	ReportStatus string    `json:"report_status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	IsVerified   bool      `json:"isVerified"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
}

type VerificationRequest struct {
	RequestID          uuid.UUID `json:"request_id"`
	UserID             uuid.UUID `json:"user_id"`
	CompanyID          uuid.UUID `json:"company_id"`
	OtpID              uuid.UUID `json:"otp_id"`
	VerificationStatus string    `json:"verification_status"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}
