// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: otp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO "OTP_Verification" (
    otp_code, expires_at, is_verified, failed_attempts, user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING otp_id, user_id, otp_code, expires_at, is_verified, failed_attempts, created_at
`

type CreateOTPParams struct {
	OtpCode        string    `json:"otp_code"`
	ExpiresAt      time.Time `json:"expires_at"`
	IsVerified     bool      `json:"is_verified"`
	FailedAttempts int32     `json:"failed_attempts"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OTPVerification, error) {
	row := q.db.QueryRowContext(ctx, createOTP,
		arg.OtpCode,
		arg.ExpiresAt,
		arg.IsVerified,
		arg.FailedAttempts,
		arg.UserID,
	)
	var i OTPVerification
	err := row.Scan(
		&i.OtpID,
		&i.UserID,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.IsVerified,
		&i.FailedAttempts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM "OTP_Verification"
WHERE otp_id = $1
`

func (q *Queries) DeleteOTP(ctx context.Context, otpID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOTP, otpID)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT otp_id, user_id, otp_code, expires_at, is_verified, failed_attempts, created_at FROM "OTP_Verification"
WHERE otp_id = $1
LIMIT 1
`

func (q *Queries) GetOTP(ctx context.Context, otpID uuid.UUID) (OTPVerification, error) {
	row := q.db.QueryRowContext(ctx, getOTP, otpID)
	var i OTPVerification
	err := row.Scan(
		&i.OtpID,
		&i.UserID,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.IsVerified,
		&i.FailedAttempts,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPs = `-- name: GetOTPs :many
SELECT otp_id, user_id, otp_code, expires_at, is_verified, failed_attempts, created_at FROM "OTP_Verification"
ORDER BY otp_id
LIMIT $1
OFFSET $2
`

type GetOTPsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetOTPs(ctx context.Context, arg GetOTPsParams) ([]OTPVerification, error) {
	rows, err := q.db.QueryContext(ctx, getOTPs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OTPVerification{}
	for rows.Next() {
		var i OTPVerification
		if err := rows.Scan(
			&i.OtpID,
			&i.UserID,
			&i.OtpCode,
			&i.ExpiresAt,
			&i.IsVerified,
			&i.FailedAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFailedAttempts = `-- name: UpdateFailedAttempts :one
UPDATE "OTP_Verification"
SET failed_attempts = $1
WHERE otp_id = $2
RETURNING otp_id, failed_attempts
`

type UpdateFailedAttemptsParams struct {
	FailedAttempts int32     `json:"failed_attempts"`
	OtpID          uuid.UUID `json:"otp_id"`
}

type UpdateFailedAttemptsRow struct {
	OtpID          uuid.UUID `json:"otp_id"`
	FailedAttempts int32     `json:"failed_attempts"`
}

func (q *Queries) UpdateFailedAttempts(ctx context.Context, arg UpdateFailedAttemptsParams) (UpdateFailedAttemptsRow, error) {
	row := q.db.QueryRowContext(ctx, updateFailedAttempts, arg.FailedAttempts, arg.OtpID)
	var i UpdateFailedAttemptsRow
	err := row.Scan(&i.OtpID, &i.FailedAttempts)
	return i, err
}
