// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BanCompany(ctx context.Context, companyID uuid.UUID) error
	BanUsers(ctx context.Context, userID uuid.UUID) error
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteCompany(ctx context.Context, companyID uuid.UUID) error
	DeleteUsers(ctx context.Context, userID uuid.UUID) error
	GetCompanies(ctx context.Context, arg GetCompaniesParams) ([]GetCompaniesRow, error)
	GetCompany(ctx context.Context, companyID uuid.UUID) (GetCompanyRow, error)
	GetCompanyForUpdate(ctx context.Context, companyID uuid.UUID) (GetCompanyForUpdateRow, error)
	GetUser(ctx context.Context, userID uuid.UUID) (GetUserRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	GetUsersForUpdate(ctx context.Context, userID uuid.UUID) (GetUsersForUpdateRow, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error)
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) (UpdateUsersRow, error)
}

var _ Querier = (*Queries)(nil)
