// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const banUsers = `-- name: BanUsers :exec
UPDATE "Users"
SET "isRestricted" = true
WHERE user_id = $1
`

func (q *Queries) BanUsers(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, banUsers, userID)
	return err
}

const createUsers = `-- name: CreateUsers :one
INSERT INTO "Users" (
    "fullName", "phoneNumber", email, password_hash
) VALUES (
    $1, $2, $3, $4
)
RETURNING user_id, "fullName", "phoneNumber", "isVerified", email, password_hash, created_at, updated_at, "isRestricted"
`

type CreateUsersParams struct {
	FullName     string `json:"fullName"`
	PhoneNumber  string `json:"phoneNumber"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM "Users"
WHERE user_id = $1
`

func (q *Queries) DeleteUsers(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUsers, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT "fullName", "phoneNumber", email, "isVerified", created_at, updated_at, "isRestricted" 
FROM "Users"
WHERE user_id = $1
LIMIT 1
`

type GetUserRow struct {
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	Email        string    `json:"email"`
	IsVerified   bool      `json:"isVerified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
}

func (q *Queries) GetUser(ctx context.Context, userID uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT "fullName", "phoneNumber", email, "isVerified", created_at, updated_at, "isRestricted"
FROM "Users"
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersRow struct {
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	Email        string    `json:"email"`
	IsVerified   bool      `json:"isVerified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersForUpdate = `-- name: GetUsersForUpdate :one
SELECT "fullName", "phoneNumber", email, "isVerified", created_at, updated_at, "isRestricted"
FROM "Users"
WHERE user_id = $1
LIMIT 1
FOR NO KEY UPDATE
`

type GetUsersForUpdateRow struct {
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	Email        string    `json:"email"`
	IsVerified   bool      `json:"isVerified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
}

func (q *Queries) GetUsersForUpdate(ctx context.Context, userID uuid.UUID) (GetUsersForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getUsersForUpdate, userID)
	var i GetUsersForUpdateRow
	err := row.Scan(
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const updateUsers = `-- name: UpdateUsers :one
UPDATE "Users"
SET 
    "fullName" = COALESCE($2, "fullName"),
    "phoneNumber" = COALESCE($3, "phoneNumber"),
    email = COALESCE($4, email),
    password_hash = COALESCE($5, password_hash),
    "isVerified" = COALESCE($6, "isVerified"),
    "isRestricted" = COALESCE($7, "isRestricted"),
    updated_at = now()
WHERE user_id = $1
RETURNING "fullName", "phoneNumber", email, "isVerified", created_at, updated_at, "isRestricted"
`

type UpdateUsersParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsVerified   bool      `json:"isVerified"`
	IsRestricted bool      `json:"isRestricted"`
}

type UpdateUsersRow struct {
	FullName     string    `json:"fullName"`
	PhoneNumber  string    `json:"phoneNumber"`
	Email        string    `json:"email"`
	IsVerified   bool      `json:"isVerified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsRestricted bool      `json:"isRestricted"`
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) (UpdateUsersRow, error) {
	row := q.db.QueryRowContext(ctx, updateUsers,
		arg.UserID,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
		arg.IsRestricted,
	)
	var i UpdateUsersRow
	err := row.Scan(
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRestricted,
	)
	return i, err
}
