// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: verification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVerificationRequest = `-- name: CreateVerificationRequest :one
INSERT INTO "Verification_Request" (
    user_id, company_id, otp_id, verification_status
) VALUES (
    $1, $2, $3, $4
)
RETURNING request_id, user_id, company_id, otp_id, verification_status, created_at, updated_at
`

type CreateVerificationRequestParams struct {
	UserID             uuid.UUID `json:"user_id"`
	CompanyID          uuid.UUID `json:"company_id"`
	OtpID              uuid.UUID `json:"otp_id"`
	VerificationStatus string    `json:"verification_status"`
}

func (q *Queries) CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) (VerificationRequest, error) {
	row := q.db.QueryRowContext(ctx, createVerificationRequest,
		arg.UserID,
		arg.CompanyID,
		arg.OtpID,
		arg.VerificationStatus,
	)
	var i VerificationRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CompanyID,
		&i.OtpID,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM "Verification_Request"
WHERE request_id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, requestID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, requestID)
	return err
}

const getVerification = `-- name: GetVerification :one
SELECT request_id, user_id, company_id, otp_id, verification_status, created_at, updated_at FROM "Verification_Request"
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetVerification(ctx context.Context, requestID uuid.UUID) (VerificationRequest, error) {
	row := q.db.QueryRowContext(ctx, getVerification, requestID)
	var i VerificationRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CompanyID,
		&i.OtpID,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerifications = `-- name: GetVerifications :many
SELECT request_id, user_id, company_id, otp_id, verification_status, created_at, updated_at FROM "Verification_Request"
ORDER BY request_id
LIMIT $1
OFFSET $2
`

type GetVerificationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetVerifications(ctx context.Context, arg GetVerificationsParams) ([]VerificationRequest, error) {
	rows, err := q.db.QueryContext(ctx, getVerifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationRequest{}
	for rows.Next() {
		var i VerificationRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.UserID,
			&i.CompanyID,
			&i.OtpID,
			&i.VerificationStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE "Verification_Request"
SET otp_id = $1
WHERE request_id = $2
RETURNING request_id, user_id, company_id, otp_id, verification_status, created_at, updated_at
`

type UpdateRequestParams struct {
	OtpID     uuid.UUID `json:"otp_id"`
	RequestID uuid.UUID `json:"request_id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (VerificationRequest, error) {
	row := q.db.QueryRowContext(ctx, updateRequest, arg.OtpID, arg.RequestID)
	var i VerificationRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CompanyID,
		&i.OtpID,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
